config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root "users#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] do
        collection do
          get :index_api, as: 'index', defaults: { format: :json }
        end
      end
      resource :likes, only: [:create, :destroy]
    end
    collection do
      get :index_api, as: 'index', defaults: { format: :json }
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :create, Post
      can :create, Comment
      can :update, Post, author_id: user.id
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :text, presence: true

  after_save :increment_post_comments_counter
  after_destroy :decrement_post_comments_counter

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_post_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: :author_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :increment_posts_counter
  before_destroy :decrement_posts_counter

  def increment_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5).to_a
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def likes?(post)
    likes.exists?(post:)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user_and_post, only: %i[destroy]
  before_action :set_user_and_post_for_new, only: %i[new create]

  def index_api
    @comments = Comment.where(post_id: params[:post_id])
    respond_to do |format|
      format.json { render json: @comments }
    end
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      flash[:success] = 'Comment Added Successfully'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:error] = 'Failed To Create Comment'
      render :new
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'Comment successfully deleted'
    redirect_to user_post_path(@user, @post)
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def set_user_and_post_for_new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :author_id).merge(author_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post: @post)

    if @like.save
      @post.increment!(:likes_counter)
      flash[:success] = 'Post liked!'
    else
      flash[:error] = 'Like creation failed'
    end

    redirect_to user_post_path(@post.author, @post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(author: current_user, post: @post)

    if @like.destroy
      @post.decrement!(:likes_counter)
      flash[:success] = 'Post unliked!'
    else
      flash[:error] = 'Unlike failed'
    end

    redirect_to user_post_path(@post.author, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_user, only: %i[index new create]
  before_action :set_post, only: [:show]
  before_action :set_default_response_format, only: [:index]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = @user.posts.includes(:comments)
    else
      @posts = Post.includes(:comments).all
    end

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find_by(id: params[:id])

    if @post.nil?
      flash[:error] = 'Post not found'
      redirect_to root_path
    else
      @user = @post.author
    end
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = Post.new(post_params)
    @post.author = @user

    if @post.save
      flash[:success] = 'New post successfully added!'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:error] = 'Post creation failed'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post successfully deleted'
    redirect_to user_posts_path(user_id: current_user.id)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_default_response_format
    request.format = :json if request.format.html?
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_current_user
      redirect_to new_user_session_path, notice: 'You have signed out successfully!'
    else
      @user = User.find(params[:id])
    end
  end

  private

  def sign_out_current_user
    sign_out(current_user)
    reset_session
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div>
  <h2 class="comments-header">Add comments</h2>
  <%= form_with(model: current_user.comments.build, url: user_post_comments_path(@user, @post), local: true) do |form| %>
    <div class="create-comment">
      <%= form.text_area :text, placeholder: 'Your comment', class: "form-control-2" %>
      <%= form.submit 'Create Comment', class: "form-btn"%>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="user-show">
  <div class="user-cont">
    <div>
      <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile" class="user-pic">
    </div>
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div class="posts-counter">
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </div>
  <div class="user-cont user-bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
    <% if @user == current_user %>
      <button class="btn-2">
        <%= link_to "New Post", new_user_post_path, class: 'btn-primary btn_2' %>
      </button>
    <% end %>
  </div>
  <div class="post-cont-container">
    <% @posts.each do  |post| %>
      <div class="post-cont">
        <h3>Post #<%= post.id %></h3>
        <p class="post-text"><%= post.text %></p>
        <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
        <%= link_to 'View', "/users/#{@user.id}/posts/#{post.id}", class: 'post-link' %>
      </div>
      <div class="comment-cont">
        <%post.recent_comments.each do |comment| %>
          <p class="pagination"><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to 'Delete', user_post_comment_path(@user, post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-post">
  <%= form_with model: @post, url: user_posts_path(@user), local: true do |f| %>
    <h2 class="comments-header">Create New Posts</h2>
    <div class="form-group">
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>
    <div class="form-group">
      <%= f.text_area :text, class: "form-control", placeholder: "Post content" %>
    </div>
    <%= f.hidden_field :comments_counter, value: 0 %>
    <%= f.hidden_field :likes_counter, value: 0 %>
    <%= f.submit "Create Post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-show-page">
  <div class="post-cont">
    <div class="post-head">
      <h3>Post #<%= @post.id %> by <%= @post.author.name %></h3>
      <p class="comments-count">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    </div>
    <p><%= @post.text %><p>
  </div>
  <% if can? :destroy, @post %>
  <%= button_to 'Delete', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>
  <div class="post-cont-container">
  <% if current_user.likes?(@post) %>
    <%= form_with(model: @like, url: user_post_likes_path(@user, @post), method: :delete, local: true) do |f| %>
      <%= f.submit 'Unlike', class: 'like-button' %>
    <% end %>
  <% else %>
    <%= form_with(model: @like, url: user_post_likes_path(@user, @post), method: :post, local: true) do |f| %>
      <%= f.submit 'Like', class: 'like-button' %>
    <% end %>
  <% end %>
</div>
  <button class="btn">
    <%= link_to 'Add Comment', "/users/#{@post.author.id}/posts/#{@post.id}/comments/new", class: 'btn-primary' %>
  </button>
  <button class="btn">
    <%= link_to 'Home', root_path, class: 'btn-primary' %>
  </button>
</div>

app/views/users/index.html.erb
<div class="user-page">
  <% @users.each do |user| %>
    <div class="user-cont">
      <div>
        <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile" class="user-pic">
      </div>
      <div class="user-info">
        <h2><%= user.name %></h2>
        <div class="posts-counter">
          <p>Number of posts: <%= user.posts_counter %></p>
          <%= link_to 'View', user_path(user), class: 'post-link' %>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
</div>

app/views/users/show.html.erb
<div class="user-show">
  <div class="user-cont">
    <div>
      <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile" class="user-pic">
    </div>
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div class="posts-counter">
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </div>
  <div class="user-cont user-bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
    <%= link_to 'Posts', "/users/#{@user.id}/posts", class: 'post-link' %>
  </div>
  <div class="user-cont user-posts">
  <h3>Recent Posts</h3>
  <% @user.posts.limit(3).each do |post| %>
    <p><%= post.title %></p>
  <% end %>
</div>
</div>